FROM ollama/ollama:latest

# Install curl (facultatif, mais utile pour des tests)
RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV OLLAMA_HOST=0.0.0.0

EXPOSE 11434

CMD ["ollama", "serve"]