services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_CONTEXT_LENGTH=1024  # Réduit de 4096 à 1024
    volumes:
      - ollama-data:/root/.ollama/models
    networks:
      - ollama-net
  app:
    container_name: app
    image: python:3.11
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - ollama-net
networks:
  ollama-net:
volumes:
  ollama-data: